apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-price-prediction
  template:
    metadata:
      labels:
        app: house-price-prediction
    spec:
      containers:
      - name: house-price-prediction
        image: house-price-prediction:latest
        ports:
        - containerPort: 5000
